### ISSUE TITLE
Attribute values are not parsed anymore?

### ISSUE THREAD

**Issue by davelina** [mrgroen/JavaScript-Snippet#3]
Hi, 

Great widget! We use it alot in our application, but for some reason it doesn't work anymore in 7.18.1 of Mendix? 

The raw javascript still works, but the attribute value is not parsed anymore and is just valued as string value for example ${your_value}.

Thanks in advance!

**Comment by mrgroen** [comment]
Hi @davelina thanks for the message.
I will look into this asap.
A lot of apps use this widget, so this will have my attention.
I will keep you updated.

**Comment by davelina** [comment]
Hi mrgroen, 

I made the mistake to not provide the necessary access rules for the attribute I want to parse. Therefore, the widget did not parse the value, but just gave the unparsed value as result. 

So, my problem is solved. Maybe this can be included in the readme so people know, but it is a very obvious problem.

**Comment by mrgroen** [comment]
I will see if i can improve the widget for this. Thanks for the update.
