### ISSUE TITLE
Option to retrieve js code from file?

### ISSUE THREAD

**Issue by brickers** [mrgroen/JavaScript-Snippet#4]
Are there any plans to read javascript from a file rather than entering the code directly in the widget? It would enable quicker development in external code editors

**Comment by mrgroen** [comment]
You can already do this by including a Javascript file to your index.html and using the modules and/or functions you defined in there in the snippets. That's how we are currently using it in most projects.

**Comment by brickers** [comment]
quite often I have a scenario where I just want to load a particular bit of code on one page or section and/or want to refresh when the section it's on is refreshed or made visible - I'd rather not have it loading for all pages, or have to split code into two blocks (with some still written in the widget)

**Comment by mrgroen** [comment]
The widget is triggered when a dataview is refreshed. Also conditional visibility in Mendix applies to the widget. So I can't seem to understand the real problem. Can you make an example (mendix) project of what you are trying to do? And explain where the problem exists?

**Comment by brickers** [comment]
What I really want is to have the widget as it is now, but instead of writing code in a text box in the widget, I can reference a .js file in my project folder. There is no additional use case that your widget doesn’t already cover, but it means I can work with .js files and a full code editor with all the nice developer that entails. Currently i need to copy and paste between my code editor and the widget, and if I am in a quick build/test cycle this can get a bit irritating.
I don’t want to include this code in the index.html file as I only want it to be loaded when it is needed - mendix is bloated enough as it is without lots of extras coming down the pipe when they may not be needed

**Comment by mrgroen** [comment]
Ah ok! But that's what I mentioned earlier.

> You can already do this by including a Javascript file to your index.html and using the modules and/or functions you defined in there in the snippets. That's how we are currently using it in most projects.

How to do this, in small steps:

- Create a JS file in your theme folder. (located in the Mendix project folder)
- Include this JS file by a script tag in your index.html file.
- Create code in the JS file (with your own IDE) in a way that you can call it from the widget. (global functions or modules)
- Insert the JavaScript Snippet widget on a Mendix page.
- Write a bit of JavaScript to call the modules/functions defined in your JS file.
- Modify code in your JS file via your IDE and rerun Mendix to see the changes.

I hope this helps you. This is a best practice we use in our projects all the time.

**Comment by brickers** [comment]
I'm aware of how to do what you've described but it still doesn't solve my issue. I will explore other options. Thanks for your time
