### ISSUE TITLE
$(document).ready() not called after open page in content.

### ISSUE THREAD

**Issue by armands9186** [mrgroen/JavaScript-Snippet#8]
The problem is that when I want to open another page by using the clickable container widget from Mendix app store, sometimes $(document).ready() function is not being called. In my case I want to find the document contains a certain class, which does, and the do some action with it. I also tried with simple alert messages.

**Comment by mrgroen** [comment]
Why are you using the ready function on document? You don't have to do this since the DOM is ready when the snippet is going to run.
