### ISSUE TITLE
Not working in Mendix 8: Error while applying context TypeError: obj.isCurrency is not a function

### ISSUE THREAD

**Issue by keving119** [mrgroen/JavaScript-Snippet#9]
After I upgraded my application to Mendix 8.1, the Javascript Widget with data source did not work anymore.
The following error is raised: Error while applying context TypeError: obj.isCurrency is not a function

I've fixed it myself by removing `|| obj.isCurrency(attr)` from line 217 in snippetjs_datasource.js
When this function is removed, the widget is working again!

**Comment by mrgroen** [comment]
Fixed in the new release. Thnx for the tip! https://github.com/mrgroen/JavaScript-Snippet/releases/tag/v1.3.0
